file_to_upload : data/KaggleV2-May-2016.csv
bucket_name : nw-manish-s3
object_name : AVC_project/raw_no_show_data.csv
cleaned_file : AVC_project/cleaned_data.csv
loc_database : AWS
populate : False
load_file_address : data/file_to_load.csv
model : AVC_project/model.pkl
model_local : data/xgboost.pkl
MYSQL_USER : admin
MYSQL_PASSWORD : Manish!123
MYSQL_HOST : nw-manish-423.cmqeocuq67tb.us-east-2.rds.amazonaws.com
MYSQL_PORT : 3306
DATABASE_NAME : msia423_db

